#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace sam3::sam31 {

struct TensorShape {
    std::array<int64_t, 4> dims;
    int rank;
};

struct TensorSpec {
    std::string_view name;
    TensorShape shape;
};

inline constexpr std::array<TensorSpec, 493> tensor_manifest = {{
    {"trk.model.interactive_sam_mask_decoder.conv_s0.bias", {{32, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.conv_s0.weight", {{32, 256, 1, 1}, 4}},
    {"trk.model.interactive_sam_mask_decoder.conv_s1.bias", {{64, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.conv_s1.weight", {{64, 256, 1, 1}, 4}},
    {"trk.model.interactive_sam_mask_decoder.iou_prediction_head.layers.0.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.iou_prediction_head.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.iou_prediction_head.layers.1.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.iou_prediction_head.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.iou_prediction_head.layers.2.bias", {{4, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.iou_prediction_head.layers.2.weight",
     {{4, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.iou_token.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.mask_tokens.weight", {{4, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.obj_score_token.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.0.layers.0.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.0.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.0.layers.1.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.0.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.0.layers.2.bias",
     {{32, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.0.layers.2.weight",
     {{32, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.1.layers.0.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.1.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.1.layers.1.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.1.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.1.layers.2.bias",
     {{32, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.1.layers.2.weight",
     {{32, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.2.layers.0.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.2.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.2.layers.1.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.2.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.2.layers.2.bias",
     {{32, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.2.layers.2.weight",
     {{32, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.3.layers.0.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.3.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.3.layers.1.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.3.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.3.layers.2.bias",
     {{32, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_hypernetworks_mlps.3.layers.2.weight",
     {{32, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.output_upscaling.0.bias", {{64, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_upscaling.0.weight", {{256, 64, 2, 2}, 4}},
    {"trk.model.interactive_sam_mask_decoder.output_upscaling.1.bias", {{64, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_upscaling.1.weight", {{64, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_upscaling.3.bias", {{32, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.output_upscaling.3.weight", {{64, 32, 2, 2}, 4}},
    {"trk.model.interactive_sam_mask_decoder.pred_obj_score_head.layers.0.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.pred_obj_score_head.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.pred_obj_score_head.layers.1.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.pred_obj_score_head.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.pred_obj_score_head.layers.2.bias", {{1, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.pred_obj_score_head.layers.2.weight",
     {{1, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.final_attn_token_to_image.k_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.final_attn_token_to_image.k_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.final_attn_token_to_image.out_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.final_attn_token_to_image.out_proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.final_attn_token_to_image.q_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.final_attn_token_to_image.q_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.final_attn_token_to_image.v_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.final_attn_token_to_image.v_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.k_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.k_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.out_"
     "proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.out_"
     "proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.q_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.q_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.v_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.v_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.k_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.k_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.out_"
     "proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.out_"
     "proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.q_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.q_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.v_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.v_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.mlp.lin1.bias",
     {{2048, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.mlp.lin1.weight",
     {{2048, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.mlp.lin2.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.mlp.lin2.weight",
     {{256, 2048, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.norm1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.norm1.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.norm2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.norm2.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.norm3.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.norm3.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.norm4.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.norm4.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.sa.k_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.sa.k_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.sa.out_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.sa.out_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.sa.q_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.sa.q_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.sa.v_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.0.sa.v_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.k_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.k_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.out_"
     "proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.out_"
     "proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.q_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.q_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.v_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.v_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.k_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.k_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.out_"
     "proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.out_"
     "proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.q_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.q_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.v_proj."
     "bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.v_proj."
     "weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.mlp.lin1.bias",
     {{2048, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.mlp.lin1.weight",
     {{2048, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.mlp.lin2.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.mlp.lin2.weight",
     {{256, 2048, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.norm1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.norm1.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.norm2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.norm2.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.norm3.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.norm3.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.norm4.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.norm4.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.sa.k_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.sa.k_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.sa.out_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.sa.out_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.sa.q_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.sa.q_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.sa.v_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.layers.1.sa.v_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_mask_decoder.transformer.norm_final_attn.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_mask_decoder.transformer.norm_final_attn.weight",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.conv_s0.bias", {{32, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.conv_s0.weight", {{32, 256, 1, 1}, 4}},
    {"trk.model.sam_mask_decoder.conv_s1.bias", {{64, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.conv_s1.weight", {{64, 256, 1, 1}, 4}},
    {"trk.model.sam_mask_decoder.iou_prediction_head.layers.0.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.iou_prediction_head.layers.0.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.iou_prediction_head.layers.1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.iou_prediction_head.layers.1.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.iou_prediction_head.layers.2.bias", {{3, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.iou_prediction_head.layers.2.weight", {{3, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.iou_token.weight", {{16, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.mask_tokens.weight", {{48, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.obj_score_token.weight", {{16, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.0.layers.0.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.0.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.0.layers.1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.0.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.0.layers.2.bias", {{32, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.0.layers.2.weight",
     {{32, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.1.layers.0.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.1.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.1.layers.1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.1.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.1.layers.2.bias", {{32, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.1.layers.2.weight",
     {{32, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.2.layers.0.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.2.layers.0.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.2.layers.1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.2.layers.1.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.2.layers.2.bias", {{32, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_hypernetworks_mlps.2.layers.2.weight",
     {{32, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.output_upscaling.0.bias", {{64, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_upscaling.0.weight", {{256, 64, 2, 2}, 4}},
    {"trk.model.sam_mask_decoder.output_upscaling.1.bias", {{64, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_upscaling.1.weight", {{64, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_upscaling.3.bias", {{32, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.output_upscaling.3.weight", {{64, 32, 2, 2}, 4}},
    {"trk.model.sam_mask_decoder.pred_obj_score_head.layers.0.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.pred_obj_score_head.layers.0.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.pred_obj_score_head.layers.1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.pred_obj_score_head.layers.1.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.pred_obj_score_head.layers.2.bias", {{1, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.pred_obj_score_head.layers.2.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.final_attn_token_to_image.k_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.final_attn_token_to_image.k_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.final_attn_token_to_image.out_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.final_attn_token_to_image.out_proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.final_attn_token_to_image.q_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.final_attn_token_to_image.q_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.final_attn_token_to_image.v_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.final_attn_token_to_image.v_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.k_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.k_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.out_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.out_proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.q_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.q_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.v_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_image_to_token.v_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.k_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.k_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.out_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.out_proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.q_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.q_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.v_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.cross_attn_token_to_image.v_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.mlp.lin1.bias", {{2048, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.mlp.lin1.weight", {{2048, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.mlp.lin2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.mlp.lin2.weight", {{256, 2048, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.norm1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.norm1.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.norm2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.norm2.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.norm3.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.norm3.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.norm4.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.norm4.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.sa.k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.sa.k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.sa.out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.sa.out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.sa.q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.sa.q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.sa.v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.0.sa.v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.k_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.k_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.out_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.out_proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.q_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.q_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.v_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_image_to_token.v_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.k_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.k_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.out_proj.bias",
     {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.out_proj.weight",
     {{256, 128, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.q_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.q_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.v_proj.bias",
     {{128, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.cross_attn_token_to_image.v_proj.weight",
     {{128, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.mlp.lin1.bias", {{2048, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.mlp.lin1.weight", {{2048, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.mlp.lin2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.mlp.lin2.weight", {{256, 2048, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.norm1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.norm1.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.norm2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.norm2.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.norm3.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.norm3.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.norm4.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.norm4.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.sa.k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.sa.k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.sa.out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.sa.out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.sa.q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.sa.q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.sa.v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.layers.1.sa.v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.sam_mask_decoder.transformer.norm_final_attn.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.sam_mask_decoder.transformer.norm_final_attn.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.0.bias", {{4, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.0.weight", {{4, 1, 2, 2}, 4}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.1.bias", {{4, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.1.weight", {{4, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.3.bias", {{16, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.3.weight", {{16, 4, 2, 2}, 4}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.4.bias", {{16, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.4.weight", {{16, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.6.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_sam_prompt_encoder.mask_downscaling.6.weight", {{256, 16, 1, 1}, 4}},
    {"trk.model.interactive_sam_prompt_encoder.no_mask_embed.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_prompt_encoder.not_a_point_embed.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_prompt_encoder.pe_layer.positional_encoding_gaussian_matrix",
     {{2, 128, 0, 0}, 2}},
    {"trk.model.interactive_sam_prompt_encoder.point_embeddings.0.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_prompt_encoder.point_embeddings.1.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_prompt_encoder.point_embeddings.2.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.interactive_sam_prompt_encoder.point_embeddings.3.weight", {{1, 256, 0, 0}, 2}},
    {"trk.model.maskmem_backbone.fuser.layers.0.dwconv.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.0.dwconv.weight", {{256, 1, 7, 7}, 4}},
    {"trk.model.maskmem_backbone.fuser.layers.0.gamma", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.0.norm.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.0.norm.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.0.pwconv1.bias", {{1024, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.0.pwconv1.weight", {{1024, 256, 0, 0}, 2}},
    {"trk.model.maskmem_backbone.fuser.layers.0.pwconv2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.0.pwconv2.weight", {{256, 1024, 0, 0}, 2}},
    {"trk.model.maskmem_backbone.fuser.layers.1.dwconv.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.1.dwconv.weight", {{256, 1, 7, 7}, 4}},
    {"trk.model.maskmem_backbone.fuser.layers.1.gamma", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.1.norm.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.1.norm.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.1.pwconv1.bias", {{1024, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.1.pwconv1.weight", {{1024, 256, 0, 0}, 2}},
    {"trk.model.maskmem_backbone.fuser.layers.1.pwconv2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.fuser.layers.1.pwconv2.weight", {{256, 1024, 0, 0}, 2}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.0.bias", {{16, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.0.weight", {{16, 32, 3, 3}, 4}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.1.bias", {{16, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.1.weight", {{16, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.10.bias", {{1024, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.10.weight", {{1024, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.12.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.12.weight", {{256, 1024, 1, 1}, 4}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.3.bias", {{64, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.3.weight", {{64, 16, 3, 3}, 4}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.4.bias", {{64, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.4.weight", {{64, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.6.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.6.weight", {{256, 64, 3, 3}, 4}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.7.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.7.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.9.bias", {{1024, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.mask_downsampler.encoder.9.weight", {{1024, 256, 3, 3}, 4}},
    {"trk.model.maskmem_backbone.pix_feat_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.maskmem_backbone.pix_feat_proj.weight", {{256, 256, 1, 1}, 4}},
    {"trk.model.interactive_mask_downsample.bias", {{1, 0, 0, 0}, 1}},
    {"trk.model.interactive_mask_downsample.weight", {{1, 1, 4, 4}, 4}},
    {"trk.model.transformer.encoder.layers.0.self_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.self_attn_k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.self_attn_out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.self_attn_out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.self_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.self_attn_q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.self_attn_v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.self_attn_v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.self_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.self_attn_k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.self_attn_out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.self_attn_out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.self_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.self_attn_q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.self_attn_v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.self_attn_v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.self_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.self_attn_k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.self_attn_out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.self_attn_out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.self_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.self_attn_q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.self_attn_v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.self_attn_v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.self_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.self_attn_k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.self_attn_out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.self_attn_out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.self_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.self_attn_q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.self_attn_v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.self_attn_v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.cross_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.cross_attn_k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.cross_attn_out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.cross_attn_out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.cross_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.cross_attn_q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.cross_attn_v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.cross_attn_v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.cross_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.cross_attn_k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.cross_attn_out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.cross_attn_out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.cross_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.cross_attn_q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.cross_attn_v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.cross_attn_v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.cross_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.cross_attn_k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.cross_attn_out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.cross_attn_out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.cross_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.cross_attn_q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.cross_attn_v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.cross_attn_v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.cross_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.cross_attn_k_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.cross_attn_out_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.cross_attn_out_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.cross_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.cross_attn_q_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.cross_attn_v_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.cross_attn_v_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.image_cross_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.image_cross_attn_k_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.image_cross_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.image_cross_attn_q_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.image_cross_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.image_cross_attn_k_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.image_cross_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.image_cross_attn_q_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.image_cross_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.image_cross_attn_k_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.image_cross_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.image_cross_attn_q_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.image_cross_attn_k_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.image_cross_attn_k_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.image_cross_attn_q_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.image_cross_attn_q_proj.weight",
     {{256, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.linear1.bias", {{2048, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.linear1.weight", {{2048, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.linear2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.linear2.weight", {{256, 2048, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.0.norm1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.norm1.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.norm2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.norm2.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.norm3.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.0.norm3.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.linear1.bias", {{2048, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.linear1.weight", {{2048, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.linear2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.linear2.weight", {{256, 2048, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.1.norm1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.norm1.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.norm2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.norm2.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.norm3.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.1.norm3.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.linear1.bias", {{2048, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.linear1.weight", {{2048, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.linear2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.linear2.weight", {{256, 2048, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.2.norm1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.norm1.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.norm2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.norm2.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.norm3.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.2.norm3.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.linear1.bias", {{2048, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.linear1.weight", {{2048, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.linear2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.linear2.weight", {{256, 2048, 0, 0}, 2}},
    {"trk.model.transformer.encoder.layers.3.norm1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.norm1.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.norm2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.norm2.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.norm3.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.layers.3.norm3.weight", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_obj_ptr_proj.layers.0.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_obj_ptr_proj.layers.0.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_obj_ptr_proj.layers.1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_obj_ptr_proj.layers.1.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.interactive_obj_ptr_proj.layers.2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.interactive_obj_ptr_proj.layers.2.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.obj_ptr_proj.layers.0.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.obj_ptr_proj.layers.0.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.obj_ptr_proj.layers.1.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.obj_ptr_proj.layers.1.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.obj_ptr_proj.layers.2.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.obj_ptr_proj.layers.2.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.obj_ptr_tpos_proj.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.obj_ptr_tpos_proj.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.image_pe_layer.positional_encoding_gaussian_matrix", {{2, 128, 0, 0}, 2}},
    {"trk.model.interactivity_no_mem_embed", {{1, 1, 256, 0}, 3}},
    {"trk.model.maskmem_tpos_enc", {{7, 1, 1, 256}, 4}},
    {"trk.model.no_obj_embed_spatial", {{16, 256, 0, 0}, 2}},
    {"trk.model.no_obj_ptr_linear.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.no_obj_ptr_linear.weight", {{256, 256, 0, 0}, 2}},
    {"trk.model.output_invalid_embed", {{16, 256, 0, 0}, 2}},
    {"trk.model.output_valid_embed", {{16, 256, 0, 0}, 2}},
    {"trk.model.transformer.encoder.norm.bias", {{256, 0, 0, 0}, 1}},
    {"trk.model.transformer.encoder.norm.weight", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.0.conv_1x1.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.0.conv_1x1.weight", {{256, 256, 1, 1}, 4}},
    {"det.backbone.vision_backbone.interactive_convs.0.conv_3x3.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.0.conv_3x3.weight", {{256, 256, 3, 3}, 4}},
    {"det.backbone.vision_backbone.interactive_convs.0.dconv_2x2_0.bias", {{512, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.0.dconv_2x2_0.weight", {{1024, 512, 2, 2}, 4}},
    {"det.backbone.vision_backbone.interactive_convs.0.dconv_2x2_1.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.0.dconv_2x2_1.weight", {{512, 256, 2, 2}, 4}},
    {"det.backbone.vision_backbone.interactive_convs.1.conv_1x1.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.1.conv_1x1.weight", {{256, 512, 1, 1}, 4}},
    {"det.backbone.vision_backbone.interactive_convs.1.conv_3x3.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.1.conv_3x3.weight", {{256, 256, 3, 3}, 4}},
    {"det.backbone.vision_backbone.interactive_convs.1.dconv_2x2.bias", {{512, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.1.dconv_2x2.weight", {{1024, 512, 2, 2}, 4}},
    {"det.backbone.vision_backbone.interactive_convs.2.conv_1x1.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.2.conv_1x1.weight", {{256, 1024, 1, 1}, 4}},
    {"det.backbone.vision_backbone.interactive_convs.2.conv_3x3.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.interactive_convs.2.conv_3x3.weight", {{256, 256, 3, 3}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.0.conv_1x1.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.0.conv_1x1.weight", {{256, 256, 1, 1}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.0.conv_3x3.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.0.conv_3x3.weight", {{256, 256, 3, 3}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.0.dconv_2x2_0.bias", {{512, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.0.dconv_2x2_0.weight", {{1024, 512, 2, 2}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.0.dconv_2x2_1.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.0.dconv_2x2_1.weight", {{512, 256, 2, 2}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.1.conv_1x1.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.1.conv_1x1.weight", {{256, 512, 1, 1}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.1.conv_3x3.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.1.conv_3x3.weight", {{256, 256, 3, 3}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.1.dconv_2x2.bias", {{512, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.1.dconv_2x2.weight", {{1024, 512, 2, 2}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.2.conv_1x1.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.2.conv_1x1.weight", {{256, 1024, 1, 1}, 4}},
    {"det.backbone.vision_backbone.propagation_convs.2.conv_3x3.bias", {{256, 0, 0, 0}, 1}},
    {"det.backbone.vision_backbone.propagation_convs.2.conv_3x3.weight", {{256, 256, 3, 3}, 4}},
}};

static_assert(tensor_manifest.size() == 493);

}  // namespace sam3::sam31
